services:
  frontend:
    build: .
    container_name: weather-frontend
    ports:
      - "8080:80"
    depends_on:
    - api
  
  api:
    build: ./api
    container_name: weather-api
    ports:
      - "5001:5000"