apiVersion: v1
kind: Secret # Creates a secret object

metadata:
  name: weather-secret

type: Opaque # Tells kubernetes this is a generic secret

stringData: # Way to keep secrets
  WEATHER_API_KEY: "my-secret-api-key"